# Generated by Django 3.1 on 2021-03-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210326_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='section',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
