# Generated by Django 3.1 on 2021-03-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='about_me',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='roll',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='section',
        ),
        migrations.AddField(
            model_name='profile',
            name='matric_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Lecturer', 'Lecturer'), ('Student', 'Student')], default='Lecturer', max_length=100),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
