# Generated by Django 3.1 on 2021-03-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_profile_roll_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='roll_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
