# Generated by Django 3.1 on 2021-03-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_roll_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Class',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
