# Generated by Django 3.1 on 2021-03-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='section',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
