# Generated by Django 3.1 on 2021-03-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210327_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Class',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='roll_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='section',
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student')], default='Teacher', max_length=100),
        ),
    ]
