# Generated by Django 3.1 on 2021-03-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210327_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Class',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='roll_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='section',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
