# Generated by Django 3.1 on 2021-03-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20210327_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subject',
            field=models.CharField(blank=True, choices=[('Computer', 'Computer'), ('Nepali', 'Nepali'), ('Social', 'Social'), ('English', 'English'), ('OBTE', 'OBTE'), ('Health', 'Health'), ('Opt Maths', 'Opt Maths')], max_length=100, null=True),
        ),
    ]
