# Generated by Django 3.1 on 2021-04-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_notification_general_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification_general',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
