# Generated by Django 3.1 on 2021-04-19 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='uploads',
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
